create table "public"."table_word-dev" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text
);


alter table "public"."table_word-dev" enable row level security;

CREATE UNIQUE INDEX "table_word-dev_pkey" ON public."table_word-dev" USING btree (id);

alter table "public"."table_word-dev" add constraint "table_word-dev_pkey" PRIMARY KEY using index "table_word-dev_pkey";

grant delete on table "public"."table_word-dev" to "anon";

grant insert on table "public"."table_word-dev" to "anon";

grant references on table "public"."table_word-dev" to "anon";

grant select on table "public"."table_word-dev" to "anon";

grant trigger on table "public"."table_word-dev" to "anon";

grant truncate on table "public"."table_word-dev" to "anon";

grant update on table "public"."table_word-dev" to "anon";

grant delete on table "public"."table_word-dev" to "authenticated";

grant insert on table "public"."table_word-dev" to "authenticated";

grant references on table "public"."table_word-dev" to "authenticated";

grant select on table "public"."table_word-dev" to "authenticated";

grant trigger on table "public"."table_word-dev" to "authenticated";

grant truncate on table "public"."table_word-dev" to "authenticated";

grant update on table "public"."table_word-dev" to "authenticated";

grant delete on table "public"."table_word-dev" to "service_role";

grant insert on table "public"."table_word-dev" to "service_role";

grant references on table "public"."table_word-dev" to "service_role";

grant select on table "public"."table_word-dev" to "service_role";

grant trigger on table "public"."table_word-dev" to "service_role";

grant truncate on table "public"."table_word-dev" to "service_role";

grant update on table "public"."table_word-dev" to "service_role";


